name: 'First interaction'
description: 'Get started with Container actions'
author: 'GitHub'
inputs: 
  issueMessage:
    description: 'Comment to post on an individuals first issue'
  prMessage:
    description: 'Comment to post on an individuals first pull request'
  repoToken:
    description: 'Token for the repo. Can be passed in using {{ secrets.GITHUB_TOKEN }}'
runs:
  using: 'docker'
  image: 'Dockerfile'