name: First Interaction
description: Greet new users when they open their first issue or pull request
author: GitHub

branding:
  icon: message-square
  color: blue

inputs:
  github-token:
    description:
      GitHub Token with permissions to write to issues and pull requests
    required: true
    default: ${{ github.token }}
  issue-message:
    description: Comment to post on new issues by first-time contributors
  pr-message:
    description: Comment to post on new pull requests by first-time contributors

runs:
  using: node20
  main: dist/index.js
