name: First Interaction
description: Greet first-time contributors when they open an issue or PR
author: GitHub

inputs:
  issue_message:
    description: Comment to post on an individual's first issue
  pr_message:
    description: Comment to post on an individual's first pull request
  repo_token:
    description: Token with permissions to post issue and PR comments
    required: true
    default: ${{ github.token }}

runs:
  using: node24
  main: dist/index.js
name: Greetings

on:
  pull_request:
    types:
      - opened
  issues:
    types:
      - opened

permissions:
  issues: write
  pull-requests: write

jobs:
  greeting:
    name: Greet First-Time Contributors
    runs-on: ubuntu-latest

    steps:
      - uses: actions/first-interaction@v3
        with:
          issue_message: |
            # Issue Message with Markdown

            This is the message that will be displayed!
          pr_message: |
            # PR Message with Markdown

            This is the message that will be displayed!
